"""add advanced order columns

Revision ID: b5de6e474f88
Revises: a52fcba9960e
Create Date: 2026-06-26 17:19:00.979921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5de6e474f88'
down_revision: Union[str, Sequence[str], None] = 'a52fcba9960e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_reduce_only', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('is_post_only', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('time_in_force', sa.String(length=10), server_default='GTC', nullable=False))
    op.add_column('orders', sa.Column('gtd_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('iceberg_visible_qty', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('oco_link_id', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('algo_type', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('algo_params', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'algo_params')
    op.drop_column('orders', 'algo_type')
    op.drop_column('orders', 'oco_link_id')
    op.drop_column('orders', 'iceberg_visible_qty')
    op.drop_column('orders', 'gtd_timestamp')
    op.drop_column('orders', 'time_in_force')
    op.drop_column('orders', 'is_post_only')
    op.drop_column('orders', 'is_reduce_only')
    # ### end Alembic commands ###
