# app/services/instrument_registry.py
from typing import Dict, Any, List

INSTRUMENTS_REGISTRY: Dict[str, Dict[str, Any]] = {
    # Crypto
    "BTCUSD": {
        "symbol": "BTCUSD",
        "name": "Bitcoin / USD",
        "category": "crypto",
        "asset_class": "crypto",
        "provider": "binance",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 1.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 1.0,
        "tick_value": 0.01,
        "pip_value": 0.01,
        "default_price": 65000.0,
        "leverage_limit": 100.0
    },
    "BTCUSDT": {
        "symbol": "BTCUSDT",
        "name": "Bitcoin / USDT",
        "category": "crypto",
        "asset_class": "crypto",
        "provider": "binance",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 1.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 1.0,
        "tick_value": 0.01,
        "pip_value": 0.01,
        "default_price": 65000.0,
        "leverage_limit": 100.0
    },
    "ETHUSD": {
        "symbol": "ETHUSD",
        "name": "Ethereum / USD",
        "category": "crypto",
        "asset_class": "crypto",
        "provider": "binance",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 1.0,
        "min_lot": 0.01,
        "max_lot": 1000.0,
        "step_size": 0.01,
        "contract_size": 1.0,
        "tick_value": 0.01,
        "pip_value": 0.01,
        "default_price": 3500.0,
        "leverage_limit": 100.0
    },
    "ETHUSDT": {
        "symbol": "ETHUSDT",
        "name": "Ethereum / USDT",
        "category": "crypto",
        "asset_class": "crypto",
        "provider": "binance",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 1.0,
        "min_lot": 0.01,
        "max_lot": 1000.0,
        "step_size": 0.01,
        "contract_size": 1.0,
        "tick_value": 0.01,
        "pip_value": 0.01,
        "default_price": 3500.0,
        "leverage_limit": 100.0
    },
    # Forex
    "EURUSD": {
        "symbol": "EURUSD",
        "name": "Euro / US Dollar",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 5,
        "pip_size": 0.0001,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 1.08,
        "leverage_limit": 500.0
    },
    "GBPUSD": {
        "symbol": "GBPUSD",
        "name": "Great British Pound / USD",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 5,
        "pip_size": 0.0001,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 1.27,
        "leverage_limit": 500.0
    },
    "USDJPY": {
        "symbol": "USDJPY",
        "name": "US Dollar / Japanese Yen",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 3,
        "pip_size": 0.01,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 0.70,
        "pip_value": 7.0,
        "default_price": 155.0,
        "leverage_limit": 500.0
    },
    "USDCHF": {
        "symbol": "USDCHF",
        "name": "US Dollar / Swiss Franc",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 5,
        "pip_size": 0.0001,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 1.10,
        "pip_value": 11.0,
        "default_price": 0.90,
        "leverage_limit": 500.0
    },
    "AUDUSD": {
        "symbol": "AUDUSD",
        "name": "Australian Dollar / USD",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 5,
        "pip_size": 0.0001,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 0.66,
        "leverage_limit": 500.0
    },
    "NZDUSD": {
        "symbol": "NZDUSD",
        "name": "New Zealand Dollar / USD",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 5,
        "pip_size": 0.0001,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 0.61,
        "leverage_limit": 500.0
    },
    "USDCAD": {
        "symbol": "USDCAD",
        "name": "US Dollar / Canadian Dollar",
        "category": "forex",
        "asset_class": "forex",
        "provider": "twelvedata",
        "precision": 5,
        "pip_size": 0.0001,
        "lot_size": 100000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100000.0,
        "tick_value": 0.73,
        "pip_value": 7.3,
        "default_price": 1.37,
        "leverage_limit": 500.0
    },
    # Metals
    "XAUUSD": {
        "symbol": "XAUUSD",
        "name": "Gold / US Dollar",
        "category": "metals",
        "asset_class": "metals",
        "provider": "twelvedata",
        "precision": 2,
        "pip_size": 0.1,
        "lot_size": 100.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 100.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 2300.0,
        "leverage_limit": 200.0
    },
    "XAGUSD": {
        "symbol": "XAGUSD",
        "name": "Silver / US Dollar",
        "category": "metals",
        "asset_class": "metals",
        "provider": "twelvedata",
        "precision": 3,
        "pip_size": 0.01,
        "lot_size": 5000.0,
        "min_lot": 0.01,
        "max_lot": 100.0,
        "step_size": 0.01,
        "contract_size": 5000.0,
        "tick_value": 5.0,
        "pip_value": 50.0,
        "default_price": 29.0,
        "leverage_limit": 100.0
    },
    "USOIL": {
        "symbol": "USOIL",
        "name": "Crude Oil / USD",
        "category": "metals",
        "asset_class": "metals",
        "provider": "twelvedata",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 100.0,
        "min_lot": 0.1,
        "max_lot": 1000.0,
        "step_size": 0.1,
        "contract_size": 100.0,
        "tick_value": 1.0,
        "pip_value": 1.0,
        "default_price": 80.0,
        "leverage_limit": 100.0
    },
    "BRENT": {
        "symbol": "BRENT",
        "name": "Brent Crude / USD",
        "category": "metals",
        "asset_class": "metals",
        "provider": "twelvedata",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 100.0,
        "min_lot": 0.1,
        "max_lot": 1000.0,
        "step_size": 0.1,
        "contract_size": 100.0,
        "tick_value": 1.0,
        "pip_value": 1.0,
        "default_price": 85.0,
        "leverage_limit": 100.0
    },
    # Indices
    "US30": {
        "symbol": "US30",
        "name": "Dow Jones 30 Index",
        "category": "indices",
        "asset_class": "indices",
        "provider": "twelvedata",
        "precision": 1,
        "pip_size": 1.0,
        "lot_size": 10.0,
        "min_lot": 0.1,
        "max_lot": 500.0,
        "step_size": 0.1,
        "contract_size": 10.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 39000.0,
        "leverage_limit": 100.0
    },
    "NAS100": {
        "symbol": "NAS100",
        "name": "Nasdaq 100 Index",
        "category": "indices",
        "asset_class": "indices",
        "provider": "twelvedata",
        "precision": 1,
        "pip_size": 1.0,
        "lot_size": 10.0,
        "min_lot": 0.1,
        "max_lot": 500.0,
        "step_size": 0.1,
        "contract_size": 10.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 19000.0,
        "leverage_limit": 100.0
    },
    "SPX500": {
        "symbol": "SPX500",
        "name": "S&P 500 Index",
        "category": "indices",
        "asset_class": "indices",
        "provider": "twelvedata",
        "precision": 1,
        "pip_size": 1.0,
        "lot_size": 10.0,
        "min_lot": 0.1,
        "max_lot": 500.0,
        "step_size": 0.1,
        "contract_size": 10.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 5400.0,
        "leverage_limit": 100.0
    },
    "GER40": {
        "symbol": "GER40",
        "name": "DAX 40 Index",
        "category": "indices",
        "asset_class": "indices",
        "provider": "twelvedata",
        "precision": 1,
        "pip_size": 1.0,
        "lot_size": 10.0,
        "min_lot": 0.1,
        "max_lot": 500.0,
        "step_size": 0.1,
        "contract_size": 10.0,
        "tick_value": 1.0,
        "pip_value": 10.0,
        "default_price": 18000.0,
        "leverage_limit": 100.0
    },
    "UK100": {
        "symbol": "UK100",
        "name": "FTSE 100 Index",
        "category": "indices",
        "asset_class": "indices",
        "provider": "twelvedata",
        "precision": 1,
        "pip_size": 1.0,
        "lot_size": 10.0,
        "min_lot": 0.1,
        "max_lot": 500.0,
        "step_size": 0.1,
        "contract_size": 10.0,
        "tick_value": 1.25,
        "pip_value": 12.5,
        "default_price": 8200.0,
        "leverage_limit": 100.0
    },
    "JP225": {
        "symbol": "JP225",
        "name": "Nikkei 225 Index",
        "category": "indices",
        "asset_class": "indices",
        "provider": "twelvedata",
        "precision": 0,
        "pip_size": 1.0,
        "lot_size": 10.0,
        "min_lot": 0.1,
        "max_lot": 500.0,
        "step_size": 0.1,
        "contract_size": 10.0,
        "tick_value": 0.07,
        "pip_value": 0.7,
        "default_price": 38000.0,
        "leverage_limit": 100.0
    },
    # Stocks
    "AAPL": {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "category": "stocks",
        "asset_class": "stocks",
        "provider": "twelvedata",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 100.0,
        "min_lot": 0.1,
        "max_lot": 1000.0,
        "step_size": 0.1,
        "contract_size": 100.0,
        "tick_value": 1.0,
        "pip_value": 1.0,
        "default_price": 210.0,
        "leverage_limit": 20.0
    },
    "TSLA": {
        "symbol": "TSLA",
        "name": "Tesla Inc.",
        "category": "stocks",
        "asset_class": "stocks",
        "provider": "twelvedata",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 100.0,
        "min_lot": 0.1,
        "max_lot": 1000.0,
        "step_size": 0.1,
        "contract_size": 100.0,
        "tick_value": 1.0,
        "pip_value": 1.0,
        "default_price": 180.0,
        "leverage_limit": 20.0
    },
    "MSFT": {
        "symbol": "MSFT",
        "name": "Microsoft Corp.",
        "category": "stocks",
        "asset_class": "stocks",
        "provider": "twelvedata",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 100.0,
        "min_lot": 0.1,
        "max_lot": 1000.0,
        "step_size": 0.1,
        "contract_size": 100.0,
        "tick_value": 1.0,
        "pip_value": 1.0,
        "default_price": 450.0,
        "leverage_limit": 20.0
    }
}

def get_instrument_spec(symbol: str) -> Dict[str, Any]:
    """Retrieve details for a specific instrument, falling back to basic defaults if not found."""
    return INSTRUMENTS_REGISTRY.get(symbol.upper(), {
        "symbol": symbol.upper(),
        "name": symbol.upper(),
        "category": "crypto",
        "asset_class": "crypto",
        "provider": "binance",
        "precision": 2,
        "pip_size": 0.01,
        "lot_size": 1.0,
        "min_lot": 0.01,
        "max_lot": 1000.0,
        "step_size": 0.01,
        "contract_size": 1.0,
        "tick_value": 0.01,
        "pip_value": 0.01,
        "default_price": 100.0,
        "leverage_limit": 20.0
    })

def get_all_instruments() -> List[Dict[str, Any]]:
    """Return all instruments in the registry."""
    return list(INSTRUMENTS_REGISTRY.values())
