"""add_position_ticket_to_orders

Revision ID: 0bcfd26da4f5
Revises: 0c59da77d0c4
Create Date: 2026-06-27 18:09:32.435852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcfd26da4f5'
down_revision: Union[str, Sequence[str], None] = '0c59da77d0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('position_ticket', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'position_ticket')
    # ### end Alembic commands ###
