"""add_commission_and_swap_to_positions

Revision ID: 0c59da77d0c4
Revises: e3a87fad2c56
Create Date: 2026-06-27 18:08:53.668793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c59da77d0c4'
down_revision: Union[str, Sequence[str], None] = 'e3a87fad2c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('commission', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('positions', sa.Column('swap', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'swap')
    op.drop_column('positions', 'commission')
    # ### end Alembic commands ###
