"""add_user_roles_and_api_keys

Revision ID: e3a87fad2c56
Revises: b5de6e474f88
Create Date: 2026-06-26 18:08:24.854703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a87fad2c56'
down_revision: Union[str, Sequence[str], None] = 'b5de6e474f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('binance_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('binance_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bybit_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bybit_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oanda_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oanda_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('alpaca_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('alpaca_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ibkr_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ibkr_api_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mt5_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mt5_api_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mt5_api_secret')
    op.drop_column('users', 'mt5_api_key')
    op.drop_column('users', 'ibkr_api_secret')
    op.drop_column('users', 'ibkr_api_key')
    op.drop_column('users', 'alpaca_api_secret')
    op.drop_column('users', 'alpaca_api_key')
    op.drop_column('users', 'oanda_api_secret')
    op.drop_column('users', 'oanda_api_key')
    op.drop_column('users', 'bybit_api_secret')
    op.drop_column('users', 'bybit_api_key')
    op.drop_column('users', 'binance_api_secret')
    op.drop_column('users', 'binance_api_key')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
