// src/components/IndicatorLibrary/indicatorData.ts

export interface IndicatorDef {
  id: string;
  name: string;
  acronym: string;
  category: string;
  tags: string[];
  shortDesc: string;
  fullDesc: string;
  author: string;
  rating: number;
  downloads: number;
  isVerified: boolean;
  isBuiltIn: boolean;
  isCommunity: boolean;
  isMyScript: boolean;
  isAiRecommended: boolean;
  defaultInputs: Record<string, any>;
  outputType: 'Overlay' | 'Sub-pane' | 'Histogram' | 'Chart Pattern';
  previewType: 'lines' | 'bands' | 'histogram' | 'levels' | 'cloud' | 'profile';
  documentation: string;
  exampleUsage: string;
}

export const INDICATOR_DATABASE: IndicatorDef[] = [
  // --- MOVING AVERAGES & TREND ---
  {
    id: 'ema20',
    name: 'Exponential Moving Average (EMA 20)',
    acronym: 'EMA 20',
    category: 'Moving Averages',
    tags: ['ema', 'moving average', 'trend', 'exponential', '20'],
    shortDesc: 'Fast exponential moving average for short-term momentum and dynamic support.',
    fullDesc: 'The Exponential Moving Average (EMA) places a greater weight and significance on the most recent data points. EMA 20 is heavily used by institutional day traders to gauge micro-trend direction.',
    author: 'Quantum Core',
    rating: 4.9,
    downloads: 245000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Period: 20, Source: 'Close', Offset: 0 },
    outputType: 'Overlay',
    previewType: 'lines',
    documentation: 'Applies exponential weighting factor k = 2 / (N + 1). Reacts faster to price changes than Simple Moving Average.',
    exampleUsage: 'Buy when price pulls back to test EMA 20 during an established uptrend.'
  },
  {
    id: 'ema50',
    name: 'Exponential Moving Average (EMA 50)',
    acronym: 'EMA 50',
    category: 'Moving Averages',
    tags: ['ema', 'moving average', 'trend', 'medium term', '50'],
    shortDesc: 'Medium-term trend filter widely tracked by algo traders and prop desks.',
    fullDesc: 'EMA 50 identifies intermediate market direction. Crossovers with EMA 20 or EMA 200 signal structural regime changes.',
    author: 'Quantum Core',
    rating: 4.8,
    downloads: 198000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { Period: 50, Source: 'Close', Offset: 0 },
    outputType: 'Overlay',
    previewType: 'lines',
    documentation: 'Calculated over a 50-period window to smooth noise while retaining medium-term sensitivity.',
    exampleUsage: 'Look for EMA 20 crossing above EMA 50 to confirm a medium-term Golden Cross setup.'
  },
  {
    id: 'ema200',
    name: 'Exponential Moving Average (EMA 200)',
    acronym: 'EMA 200',
    category: 'Moving Averages',
    tags: ['ema', 'moving average', 'trend', 'long term', '200', 'macro'],
    shortDesc: 'The definitive institutional trend baseline used across Wall Street and crypto markets.',
    fullDesc: 'The 200 EMA serves as the primary divide between long-term bull and bear market environments across high-frequency and macro funds.',
    author: 'Quantum Core',
    rating: 5.0,
    downloads: 380000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Period: 200, Source: 'Close', Offset: 0 },
    outputType: 'Overlay',
    previewType: 'lines',
    documentation: 'Macro trend baseline. Price above 200 EMA indicates long-term bullish bias.',
    exampleUsage: 'Only take long setups when price is trading comfortably above the 200 EMA.'
  },
  {
    id: 'vwap',
    name: 'Volume Weighted Average Price (VWAP)',
    acronym: 'VWAP',
    category: 'Volume',
    tags: ['vwap', 'volume', 'institutional', 'benchmark', 'order flow'],
    shortDesc: 'Institutional execution benchmark calculating true volume-weighted fair value.',
    fullDesc: 'VWAP gives the average price a security has traded at throughout the day, based on both volume and price. It is the gold standard benchmark for institutional execution algorithms.',
    author: 'Quantum Core',
    rating: 5.0,
    downloads: 410000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Anchor: 'Session', StdDevBands: true, Multiplier: 1.0 },
    outputType: 'Overlay',
    previewType: 'bands',
    documentation: 'VWAP = Sum(Volume * Price) / Sum(Volume). Includes +1/-1 standard deviation volatility bands.',
    exampleUsage: 'Institutions accumulate below session VWAP and distribute above VWAP upper band.'
  },
  {
    id: 'supertrend',
    name: 'Supertrend AI Volatility Filter',
    acronym: 'SUPERTREND',
    category: 'Trend',
    tags: ['supertrend', 'atr', 'trend', 'trailing stop', 'signals'],
    shortDesc: 'ATR-based adaptive trend-following indicator with automatic buy/sell stops.',
    fullDesc: 'Supertrend uses Average True Range (ATR) to measure market volatility and construct dynamic upper/lower trailing stop bands that flip direction upon breakout.',
    author: 'Quantum Core',
    rating: 4.8,
    downloads: 185000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { ATR_Period: 10, Multiplier: 3.0 },
    outputType: 'Overlay',
    previewType: 'levels',
    documentation: 'Upper Band = (High + Low) / 2 + (Multiplier * ATR). Flips green for Bullish, red for Bearish.',
    exampleUsage: 'Stay long while Supertrend line is green; close position immediately when line flips red.'
  },
  {
    id: 'ichimoku',
    name: 'Ichimoku Kinko Hyo (Cloud)',
    acronym: 'ICHIMOKU',
    category: 'Trend',
    tags: ['ichimoku', 'cloud', 'tenkan', 'kijun', 'senkou', 'trend'],
    shortDesc: 'Comprehensive Japanese trend, momentum, and support/resistance system.',
    fullDesc: 'Ichimoku Cloud defines support and resistance, identifies trend direction, gauges momentum, and provides trading signals in a single visual framework.',
    author: 'Quantum Core',
    rating: 4.7,
    downloads: 142000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { ConversionLine: 9, BaseLine: 26, SpanB: 52, Displacement: 26 },
    outputType: 'Overlay',
    previewType: 'cloud',
    documentation: 'Kumo (Cloud) is formed between Senkou Span A and Span B. Green cloud = bullish, red = bearish.',
    exampleUsage: 'Bullish breakout occurs when price crosses above the Kumo Cloud with Tenkan > Kijun.'
  },

  // --- VOLATILITY & BANDS ---
  {
    id: 'bb',
    name: 'Bollinger Bands',
    acronym: 'BB',
    category: 'Volatility',
    tags: ['bb', 'bollinger', 'volatility', 'squeeze', 'mean reversion'],
    shortDesc: 'Statistical standard deviation envelope surrounding a simple moving average.',
    fullDesc: 'Bollinger Bands consist of a middle N-period moving average and two outer bands set N standard deviations away. Bands expand during high volatility and contract during squeezes.',
    author: 'John Bollinger (Core)',
    rating: 4.9,
    downloads: 320000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { Period: 20, StdDev: 2.0, Source: 'Close' },
    outputType: 'Overlay',
    previewType: 'bands',
    documentation: 'Band Width = (Upper - Lower) / Middle. Expect explosive volatility expansion after a band squeeze.',
    exampleUsage: 'Trade mean-reversion bounces off the outer bands during ranging markets.'
  },
  {
    id: 'atr',
    name: 'Average True Range (ATR)',
    acronym: 'ATR',
    category: 'Volatility',
    tags: ['atr', 'volatility', 'range', 'stop loss', 'position sizing'],
    shortDesc: 'Measures absolute market volatility across gap openings and true ranges.',
    fullDesc: 'ATR measures price volatility by decomposing the entire range of an asset for that period. It is essential for calculated stop-loss placement and risk sizing.',
    author: 'Quantum Core',
    rating: 4.8,
    downloads: 210000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { Period: 14, Smoothing: 'RMA' },
    outputType: 'Sub-pane',
    previewType: 'lines',
    documentation: 'True Range = Max(High - Low, |High - PrevClose|, |Low - PrevClose|). ATR is 14-period RMA of TR.',
    exampleUsage: 'Set Stop Loss distance to 1.5x ATR below your entry price to prevent noise stop-outs.'
  },

  // --- OSCILLATORS & MOMENTUM ---
  {
    id: 'rsi',
    name: 'Relative Strength Index (RSI)',
    acronym: 'RSI',
    category: 'Oscillators',
    tags: ['rsi', 'relative strength', 'oscillator', 'overbought', 'oversold', 'divergence'],
    shortDesc: 'Classic momentum oscillator measuring velocity and magnitude of price changes.',
    fullDesc: 'RSI measures the speed and change of price movements on a scale from 0 to 100. Readings above 70 indicate overbought conditions, while readings below 30 indicate oversold conditions.',
    author: 'J. Welles Wilder (Core)',
    rating: 5.0,
    downloads: 520000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Length: 14, Overbought: 70, Oversold: 30 },
    outputType: 'Sub-pane',
    previewType: 'lines',
    documentation: 'RS = Average Gain / Average Loss over N periods. RSI = 100 - (100 / (1 + RS)).',
    exampleUsage: 'Look for bullish divergence where price makes lower lows while RSI prints higher lows.'
  },
  {
    id: 'macd',
    name: 'MACD (Moving Average Convergence Divergence)',
    acronym: 'MACD',
    category: 'Momentum',
    tags: ['macd', 'momentum', 'signal line', 'histogram', 'crossover'],
    shortDesc: 'Trend-following momentum indicator displaying relationship between two EMAs.',
    fullDesc: 'MACD is calculated by subtracting the 26-period EMA from the 12-period EMA. A 9-period EMA signal line is plotted on top to trigger buy/sell crossovers.',
    author: 'Gerald Appel (Core)',
    rating: 4.9,
    downloads: 480000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { FastLength: 12, SlowLength: 26, SignalLength: 9 },
    outputType: 'Sub-pane',
    previewType: 'histogram',
    documentation: 'MACD Line = EMA(12) - EMA(26). Signal Line = EMA(9, MACD Line). Histogram = MACD - Signal.',
    exampleUsage: 'Buy when MACD Line crosses above Signal Line below the zero baseline.'
  },
  {
    id: 'stochastic',
    name: 'Stochastic Oscillator',
    acronym: 'STOCH',
    category: 'Oscillators',
    tags: ['stochastic', 'stoch', 'oscillator', 'momentum', 'k d lines'],
    shortDesc: 'Compares a specific closing price to a range of prices over a given period.',
    fullDesc: 'Stochastic Oscillator follows the speed or momentum of price. %K is the main line, and %D is its 3-period simple moving average signal line.',
    author: 'George Lane (Core)',
    rating: 4.6,
    downloads: 165000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { K_Period: 14, D_Period: 3, Smooth: 3 },
    outputType: 'Sub-pane',
    previewType: 'lines',
    documentation: '%K = 100 * (Current Close - Lowest Low) / (Highest High - Lowest Low).',
    exampleUsage: 'Cross of %K above %D below 20 triggers a strong oversold buy signal.'
  },
  {
    id: 'adx',
    name: 'Average Directional Index (ADX / DI)',
    acronym: 'ADX',
    category: 'Momentum',
    tags: ['adx', 'directional index', 'trend strength', 'di plus di minus'],
    shortDesc: 'Quantifies trend strength independent of direction.',
    fullDesc: 'ADX measures the overall strength of a trend. Readings above 25 indicate a strong trending market, while readings below 20 indicate a weak or non-trending market.',
    author: 'Quantum Core',
    rating: 4.7,
    downloads: 115000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { ADX_Length: 14, DI_Length: 14, Threshold: 25 },
    outputType: 'Sub-pane',
    previewType: 'lines',
    documentation: 'Includes +DI (Bullish Directional Indicator) and -DI (Bearish Directional Indicator).',
    exampleUsage: 'Filter out trend-following trades when ADX is below 20 (ranging market).'
  },

  // --- SMART MONEY CONCEPTS & ORDER FLOW ---
  {
    id: 'ob',
    name: 'Institutional Order Block Detector (SMC)',
    acronym: 'ORDER BLOCK',
    category: 'Smart Money Concepts',
    tags: ['order block', 'ob', 'smc', 'smart money', 'institutional', 'liquidity'],
    shortDesc: 'Automated detection of institutional liquidity pools and order blocks.',
    fullDesc: 'Detects the last opposite-color candle prior to an aggressive displacement wave where smart money institutions accumulated or distributed heavy volume.',
    author: 'SMC Quant Labs',
    rating: 4.9,
    downloads: 290000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { DisplacementThreshold: 2.0, MaxBlocks: 5, MitigationFilter: true },
    outputType: 'Overlay',
    previewType: 'levels',
    documentation: 'Renders mitigated vs unmitigated bullish & bearish order block zones with target alerts.',
    exampleUsage: 'Enter limit orders on first retest of an unmitigated 15m Bullish Order Block.'
  },
  {
    id: 'fvg',
    name: 'Smart Money Fair Value Gap (FVG)',
    acronym: 'FVG',
    category: 'Smart Money Concepts',
    tags: ['fvg', 'fair value gap', 'imbalance', 'smc', 'liquidity void'],
    shortDesc: 'Highlights 3-candle price imbalances and unfulfilled liquidity voids.',
    fullDesc: 'Fair Value Gaps occur when price moves aggressively in one direction without overlapping wick coverage between Candle 1 high and Candle 3 low.',
    author: 'ICT Quant Desk',
    rating: 4.9,
    downloads: 310000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { MinGapTicks: 5, FillType: 'Consequent Encroachment', AutoHideFilled: true },
    outputType: 'Overlay',
    previewType: 'bands',
    documentation: 'Highlights 50% midpoint (Consequent Encroachment) where price usually bounces.',
    exampleUsage: 'Set take-profit targets at opposing HTF Fair Value Gaps.'
  },
  {
    id: 'volProfile',
    name: 'Point of Control (Volume Profile POC)',
    acronym: 'POC / VP',
    category: 'Volume Profile',
    tags: ['volume profile', 'poc', 'point of control', 'value area', 'market profile', 'vpvr'],
    shortDesc: 'Displays volume distribution by price level, identifying POC and Value Area.',
    fullDesc: 'Volume Profile calculates the total volume traded at specific price levels over a selected time window, highlighting Point of Control (POC), Value Area High (VAH), and Value Area Low (VAL).',
    author: 'Quantum Core',
    rating: 5.0,
    downloads: 360000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Bins: 50, ValueAreaPct: 70, Layout: 'Right' },
    outputType: 'Overlay',
    previewType: 'profile',
    documentation: 'POC is the exact price level with the highest traded volume in the visible range.',
    exampleUsage: 'Price acceptance inside Value Area favors rotation toward Point of Control.'
  },
  {
    id: 'cvd',
    name: 'Cumulative Volume Delta (CVD)',
    acronym: 'CVD',
    category: 'Order Flow',
    tags: ['cvd', 'delta', 'order flow', 'cumulative volume delta', 'absorption'],
    shortDesc: 'Real-time cumulative sum of net buying vs net selling market order flow.',
    fullDesc: 'CVD tracks aggressor buy volume minus aggressor sell volume over time to expose hidden institutional absorption and aggressive market sweeps.',
    author: 'OrderFlow Pro',
    rating: 4.9,
    downloads: 175000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Anchor: 'Session', DisplayType: 'Candles' },
    outputType: 'Sub-pane',
    previewType: 'histogram',
    documentation: 'Positive delta = net aggressor buying; negative delta = net aggressor selling.',
    exampleUsage: 'Spot bullish absorption when price makes a lower low while CVD makes a higher high.'
  },
  {
    id: 'pivots',
    name: 'Institutional Pivot Points (Standard / Camarilla)',
    acronym: 'PIVOTS',
    category: 'Institutional',
    tags: ['pivots', 'support', 'resistance', 'camarilla', 'floor pivots', 'daily levels'],
    shortDesc: 'Automated floor and Camarilla support/resistance levels.',
    fullDesc: 'Calculates key mathematical pivot levels (P, R1-R4, S1-S4) based on previous session high, low, and close data.',
    author: 'Quantum Core',
    rating: 4.6,
    downloads: 128000,
    isVerified: true,
    isBuiltIn: true,
    isCommunity: false,
    isMyScript: false,
    isAiRecommended: false,
    defaultInputs: { Type: 'Camarilla', Timeframe: 'Daily' },
    outputType: 'Overlay',
    previewType: 'levels',
    documentation: 'Camarilla H3/L3 levels act as key mean reversion boundaries; H4/L4 trigger momentum breakouts.',
    exampleUsage: 'Look for reversal entries at L3 support with tight stop below L4.'
  },

  // --- AI & COMMUNITY INDICATORS ---
  {
    id: 'ai_neural_trend',
    name: 'Neural AI Regime Classifier',
    acronym: 'AI REGIME',
    category: 'AI Indicators',
    tags: ['ai', 'neural network', 'machine learning', 'regime', 'trend', 'ai indicators'],
    shortDesc: 'Deep learning neural network model predicting market regime shifts.',
    fullDesc: 'Trained on 10+ years of high-frequency tick data, this AI model classifies current market structure into Trending, Ranging, or Volatility Expansion regimes.',
    author: 'DeepMind Quant Team',
    rating: 5.0,
    downloads: 215000,
    isVerified: true,
    isBuiltIn: false,
    isCommunity: true,
    isMyScript: false,
    isAiRecommended: true,
    defaultInputs: { Sensitivity: 0.85, ModelVersion: 'v4.2-Transformer' },
    outputType: 'Overlay',
    previewType: 'cloud',
    documentation: 'Outputs probabilistic confidence score (0-100%) for regime transitions.',
    exampleUsage: 'Execute trend strategies only when Neural AI confidence is > 85%.'
  },
  {
    id: 'pine_custom_scalper',
    name: 'Quantum High-Freq Scalper Pine v5',
    acronym: 'HF SCALPER',
    category: 'Custom Indicators',
    tags: ['pine script', 'custom', 'scalper', 'hft', 'my scripts', 'strategy'],
    shortDesc: 'Custom Pine v5 script for ultra-fast scalp signals with dynamic TP/SL.',
    fullDesc: 'Custom script developed in Quantum Script Editor. Combines micro-structure delta imbalance with EMA velocity.',
    author: 'You (Local User)',
    rating: 5.0,
    downloads: 1,
    isVerified: true,
    isBuiltIn: false,
    isCommunity: false,
    isMyScript: true,
    isAiRecommended: false,
    defaultInputs: { FastLength: 5, Multiplier: 1.5, TakeProfitRatio: 2.0 },
    outputType: 'Overlay',
    previewType: 'levels',
    documentation: 'User script compiled locally via Quantum Script Engine.',
    exampleUsage: 'Generates green/red buy-sell arrow markers on 1m chart.'
  }
];
